//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 14.0.23107.0
// 
namespace NAVDataAccess.WcfMongoService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WcfMongoService.IRequest")]
    public interface IRequest {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRequest/Query", ReplyAction="http://tempuri.org/IRequest/QueryResponse")]
        System.Threading.Tasks.Task<string> QueryAsync(string Table, string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRequest/QueryXML", ReplyAction="http://tempuri.org/IRequest/QueryXMLResponse")]
        System.Threading.Tasks.Task<string> QueryXMLAsync(string Table, string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRequest/InsertOne", ReplyAction="http://tempuri.org/IRequest/InsertOneResponse")]
        System.Threading.Tasks.Task<string> InsertOneAsync(string Table, string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRequest/Update", ReplyAction="http://tempuri.org/IRequest/UpdateResponse")]
        System.Threading.Tasks.Task<string> UpdateAsync(string Table, string Command, string query, string value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRequestChannel : NAVDataAccess.WcfMongoService.IRequest, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RequestClient : System.ServiceModel.ClientBase<NAVDataAccess.WcfMongoService.IRequest>, NAVDataAccess.WcfMongoService.IRequest {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public RequestClient() : 
                base(RequestClient.GetDefaultBinding(), RequestClient.GetDefaultEndpointAddress()) {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IRequest.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RequestClient(EndpointConfiguration endpointConfiguration) : 
                base(RequestClient.GetBindingForEndpoint(endpointConfiguration), RequestClient.GetEndpointAddress(endpointConfiguration)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RequestClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(RequestClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RequestClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(RequestClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RequestClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Threading.Tasks.Task<string> QueryAsync(string Table, string value) {
            return base.Channel.QueryAsync(Table, value);
        }
        
        public System.Threading.Tasks.Task<string> QueryXMLAsync(string Table, string value) {
            return base.Channel.QueryXMLAsync(Table, value);
        }
        
        public System.Threading.Tasks.Task<string> InsertOneAsync(string Table, string value) {
            return base.Channel.InsertOneAsync(Table, value);
        }
        
        public System.Threading.Tasks.Task<string> UpdateAsync(string Table, string Command, string query, string value) {
            return base.Channel.UpdateAsync(Table, Command, query, value);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IRequest)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IRequest)) {
                return new System.ServiceModel.EndpointAddress("http://localhost:52801/MongoRequest.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return RequestClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IRequest);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return RequestClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IRequest);
        }
        
        public enum EndpointConfiguration {
            
            BasicHttpBinding_IRequest,
        }
    }
}
